#ifndef CMAKE_BOARD_ADAFRUIT_FRUIT_JAM_H
#define CMAKE_BOARD_ADAFRUIT_FRUIT_JAM_H

#include <boards/adafruit_fruit_jam.h>

// --- PSRAM ---
#ifndef PICO_DEFAULT_PSRAM_CS_PIN
#define PICO_DEFAULT_PSRAM_CS_PIN 47
#endif

// --- HSTX ---
#ifndef PICO_DEFAULT_HSTX_CK_PIN
#define PICO_DEFAULT_HSTX_CK_PIN 12
#endif
#ifndef PICO_DEFAULT_HSTX_D0_PIN
#define PICO_DEFAULT_HSTX_D0_PIN 14
#endif
#ifndef PICO_DEFAULT_HSTX_D1_PIN
#define PICO_DEFAULT_HSTX_D1_PIN 16
#endif
#ifndef PICO_DEFAULT_HSTX_D2_PIN
#define PICO_DEFAULT_HSTX_D2_PIN 18
#endif
#ifndef PICO_DEFAULT_HSTX_INV
#define PICO_DEFAULT_HSTX_INV false
#endif

#endif

