#ifndef BOARD_ADAFRUIT_FEATHER_RP2350_H
#define BOARD_ADAFRUIT_FEATHER_RP2350_H

#include <boards/adafruit_feather_rp2350.h>

// --- PSRAM ---
#ifndef PICO_DEFAULT_PSRAM_CS_PIN
#define PICO_DEFAULT_PSRAM_CS_PIN 8
#endif

// --- HSTX ---
#ifndef PICO_DEFAULT_HSTX_CK_PIN
#define PICO_DEFAULT_HSTX_CK_PIN 14
#endif
#ifndef PICO_DEFAULT_HSTX_D0_PIN
#define PICO_DEFAULT_HSTX_D0_PIN 18
#endif
#ifndef PICO_DEFAULT_HSTX_D1_PIN
#define PICO_DEFAULT_HSTX_D1_PIN 16
#endif
#ifndef PICO_DEFAULT_HSTX_D2_PIN
#define PICO_DEFAULT_HSTX_D2_PIN 12
#endif
#ifndef PICO_DEFAULT_HSTX_INV
#define PICO_DEFAULT_HSTX_INV true
#endif

#endif
