#ifndef BOARD_ADAFRUIT_FEATHER_RP2040_RFM69_H
#define BOARD_ADAFRUIT_FEATHER_RP2040_RFM69_H

#include <boards/adafruit_feather_rp2040.h>

// Differences between Feather RP2040 vanilla and RFM69
#undef  PICO_DEFAULT_WS2812_PIN

// --- NEOPIXEL ---
#ifndef PICO_DEFAULT_WS2812_PIN
#define PICO_DEFAULT_WS2812_PIN 4
#endif

// --- SPI1 assignments ---
#ifndef PICO_DEFAULT_SPI1_SCK_PIN
#define PICO_DEFAULT_SPI1_SCK_PIN 10
#endif

#ifndef PICO_DEFAULT_SPI1_TX_PIN
#define PICO_DEFAULT_SPI1_TX_PIN 11
#endif

#ifndef PICO_DEFAULT_SPI1_RX_PIN
#define PICO_DEFAULT_SPI1_RX_PIN 12
#endif

#ifndef PICO_DEFAULT_SPI1_CS_PIN
#define PICO_DEFAULT_SPI1_CS_PIN 13
#endif

// SCK  SCK GP10 GP14 GP18
// MOSI TX  GP11 GP15 GP19
// MISO RX  GP12 GP8  GP16 GP20
// CSn  CS  GP13 GP9  GP17 GP21

#endif
